import { ClerkProvider } from '@clerk/nextjs';
import { Analytics } from '@vercel/analytics/next';
import type { Metadata } from 'next';
import MainFooter from '../components/Footer';
import { Navbar } from '../components/Navbar';
import ReactQueryClientProvider from '../components/react-query-client-provider';
import './globals.css';

export const metadata: Metadata = {
  title: 'PurePlate',
  description: 'Generated By Derkaoui Yassir',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ReactQueryClientProvider>
        <html lang="en">
          <body className="antialiased">
            <Navbar />
            {children}
            <MainFooter />
            <Analytics />
          </body>
        </html>
      </ReactQueryClientProvider>
    </ClerkProvider>
  );
}
